uploadConfig: S:/TOOLS/.Hudyma_projects/Rozetka2025/src/main/resources/static/img/products
basePathConfig: S:/TOOLS/.Hudyma_projects/Rozetka2025/src/main/resources/static

rozetka2025:
  store:
    version: 0.0.4
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rozetka2025
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: Rozetka2025

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.client.RestTemplate: INFO
    org.springframework.web.HttpLogging: WARN
    org.springframework.boot.context.config: DEBUG
    org.springframework.data.repository.config.RepositoryConfigurationExtensionSupport: WARN